### ISSUE TITLE
moderator invitations are not sent at the moment

### ISSUE THREAD

**Issue by fuzzylogic2000** [liqd/a4-product#119]
the invitations are in background tasks, but are not send because default language is not set?!:

```
Traceback (most recent call last):
  File "/home/django/django/lib/python3.4/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/home/django/django/lib/python3.4/site-packages/adhocracy4/emails/tasks.py", line 14, in send_async
    return cls().dispatch(object, *args, **kwargs)
  File "/home/django/django/lib/python3.4/site-packages/adhocracy4/emails/base.py", line 97, in dispatch
    (subject, text, html) = self.render(template, context)
  File "/home/django/django/lib/python3.4/site-packages/adhocracy4/emails/base.py", line 67, in render
    languages = self.get_languages(context['receiver'])
  File "/home/django/django/lib/python3.4/site-packages/meinberlin/apps/contrib/emails.py", line 12, in get_languages
    return [settings.DEFAULT_LANGUAGE, self.fallback_language]
  File "/home/django/django/lib/python3.4/site-packages/django/conf/__init__.py", line 57, in __getattr__
    val = getattr(self._wrapped, name)
AttributeError: 'Settings' object has no attribute 'DEFAULT_LANGUAGE'
```

**Comment by kleingeist** [comment]
there is still a problem, as the verbose_name tags are not available
we have to enable the app meinberlin_notifications for that

**Comment by kleingeist** [comment]
there is also another issue with missing urls. this is probably due to the missing urls from meinberlin/projects where the invitiation routes are defined.
in the long run it would make sense to refactor and split invitiations form the projects app

```
NoReverseMatch at /dashboard/projects/spatial-idea-collection-mapidea/moderators/
Reverse for 'project-moderator-invite-detail' not found. 'project-moderator-invite-detail' is not a valid view function or pattern name.
```
